name: Create and publish the quit-test Docker image

on:
  workflow_dispatch:
  push:
    branches: [ "quit-test" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-image:
    runs-on: ubuntu-latest

    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    permissions:
      contents: read
      packages: write

    name: ${{ matrix.config.r }}

    strategy:
      fail-fast: false
      matrix:
        config:
        #- { r: 'devel' }
        #- { r: 'next'  }
        - { r: '4.4.1' }

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: quit-test
        
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}  #
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }} 

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

